# This file was generated by GoReleaser. DO NOT EDIT.
cask "ghprofile" do
  version "0.2.6"

  on_macos do
    on_arm do
      sha256 "4b395dfca9548680df39b3e5aec7a69e9a03ae7f2b29531e783a549b5c1a3115"
      url "https://github.com/Tessie475/ghprofile/releases/download/v#{version}/ghprofile_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "ff98e74baad7eb2c4c4b4a91a7e88b4d91df0bb4ba67c99cf0190dc759761198"
      url "https://github.com/Tessie475/ghprofile/releases/download/v#{version}/ghprofile_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "f4a4c914277b1f1e88f2e26e96d16f4f57cf66dac9bcdb7ec57647217c4348d7"
      url "https://github.com/Tessie475/ghprofile/releases/download/v#{version}/ghprofile_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "dc8b088a721561a8c231330916edd0b8062f54b4751dfc4ccfa868004798b2a7"
      url "https://github.com/Tessie475/ghprofile/releases/download/v#{version}/ghprofile_#{version}_linux_amd64.tar.gz"
    end
  end

  name "ghprofile"
  desc "Use two GitHub accounts from one machine, in two commands"
  homepage "https://github.com/Tessie475/ghprofile"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ghprofile"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ghprofile"]
    end
  end

  # No zap stanza required
end
