# This file was generated by GoReleaser. DO NOT EDIT.
cask "ghprofile" do
  version "0.2.3"

  on_macos do
    on_arm do
      sha256 "9c2ede0a91f512c209f39975ed7d281c9830fcf0a93e6311177ca6081229b0b4"
      url "https://github.com/Tessie475/ghprofile/releases/download/v#{version}/ghprofile_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "4372d8a008847cb02f3823fe681525cd5a30cade6a022947e0372221895fc123"
      url "https://github.com/Tessie475/ghprofile/releases/download/v#{version}/ghprofile_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "4c1b202813494b054fdcf2a351cecfae8e03e446de9640f36dbdb9fe2826fdbf"
      url "https://github.com/Tessie475/ghprofile/releases/download/v#{version}/ghprofile_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "b3b2b48d695a169404016f576319d896fddb5a15a7016dde703ec816d50de387"
      url "https://github.com/Tessie475/ghprofile/releases/download/v#{version}/ghprofile_#{version}_linux_amd64.tar.gz"
    end
  end

  name "ghprofile"
  desc "Use two GitHub accounts from one machine, in two commands"
  homepage "https://github.com/Tessie475/ghprofile"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ghprofile"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ghprofile"]
    end
  end

  # No zap stanza required
end
