# This file was generated by GoReleaser. DO NOT EDIT.
cask "ghprofile" do
  version "0.2.2"

  on_macos do
    on_arm do
      sha256 "bd74af85fdb2f3ddeb6466884825eee2086165af43f0d464477f575eb3b7d302"
      url "https://github.com/Tessie475/ghprofile/releases/download/v#{version}/ghprofile_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "0eefe9e418f5882860372cedb0b00b3d02697bbe7c5acb37ba1b1cfb3df4ff70"
      url "https://github.com/Tessie475/ghprofile/releases/download/v#{version}/ghprofile_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "a1bf431702c3bb39ae6e8977b9fd73509374f7457f7c750182e54740f86c6299"
      url "https://github.com/Tessie475/ghprofile/releases/download/v#{version}/ghprofile_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "b70b8d60d12f3820e41205d890d9e893a218a78fc25db613a54ad5a243e7db3e"
      url "https://github.com/Tessie475/ghprofile/releases/download/v#{version}/ghprofile_#{version}_linux_amd64.tar.gz"
    end
  end

  name "ghprofile"
  desc "Use two GitHub accounts from one machine, in two commands"
  homepage "https://github.com/Tessie475/ghprofile"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ghprofile"

  # No zap stanza required
end
